version: 2.1
workflows:
  update-pr:
    jobs:
      - update-pr:
          filters:
            branches:
              only: /master/
  build:
    jobs:
      - hello
jobs:
  update-pr:
    docker:
      - image: alpine:3.12.0
    steps:
      - run:
          name: install tools
          command: |
            apk add git bash
      - checkout
      - run:
          name: update pr
          command: bash ci/update-pr.sh
  hello:
    docker:
      - image: plugins/base
    steps:
      - run:
          name: install tools
          command: |
            apk add --no-cache bash ca-certificates
            apk add --no-cache perl curl
            apk add --no-cache openssh
            apk add --no-cache git
      - checkout
      - run:
          name: hello
          command: bash ci/hello.sh
